version: 2
updates:
  # Rust dependencies for main project
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "IvanLi-CN"
    assignees:
      - "IvanLi-CN"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"

  # Rust dependencies for flash_programmer
  - package-ecosystem: "cargo"
    directory: "/flash_programmer"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "01:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "IvanLi-CN"
    assignees:
      - "IvanLi-CN"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
      - "flash-programmer"

  # Rust dependencies for flash_test_image
  - package-ecosystem: "cargo"
    directory: "/flash_test_image"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "IvanLi-CN"
    assignees:
      - "IvanLi-CN"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
      - "flash-test-image"

  # Node.js dependencies for development tools
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "IvanLi-CN"
    assignees:
      - "IvanLi-CN"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "nodejs"
      - "dev-tools"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "IvanLi-CN"
    assignees:
      - "IvanLi-CN"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"
