# Markdownlint configuration for sk150c-kit project
# Optimized for both English and Chinese documentation

# Global configuration
config:
  # Disable overly strict rules for better Chinese content support
  MD013: false  # Line length - disabled for Chinese content
  MD033: false  # Inline HTML - allow HTML in markdown
  MD041: false  # First line in file should be a top level heading - allow flexibility

  # Keep important formatting rules
  MD001: true   # Heading levels should only increment by one level at a time
  MD003:        # Heading style
    style: "atx"  # Use # style headings
  MD004:        # Unordered list style
    style: "dash"  # Use - for unordered lists
  MD005: true   # Inconsistent indentation for list items at the same level
  MD007:        # Unordered list indentation
    indent: 2   # 2 spaces for list indentation
  MD009: true   # Trailing spaces
  MD010: true   # Hard tabs
  MD011: true   # Reversed link syntax
  MD012: true   # Multiple consecutive blank lines
  MD014: true   # Dollar signs used before commands without showing output
  MD018: true   # No space after hash on atx style heading
  MD019: true   # Multiple spaces after hash on atx style heading
  MD020: true   # No space inside hashes on closed atx style heading
  MD021: true   # Multiple spaces inside hashes on closed atx style heading
  MD022: true   # Headings should be surrounded by blank lines
  MD023: true   # Headings must start at the beginning of the line
  MD024: true   # Multiple headings with the same content
  MD025: true   # Multiple top level headings in the same document
  MD026: true   # Trailing punctuation in heading
  MD027: true   # Multiple spaces after blockquote symbol
  MD028: true   # Blank line inside blockquote
  MD029:        # Ordered list item prefix
    style: "ordered"  # Use 1. 2. 3. style
  MD030: true   # Spaces after list markers
  MD031: true   # Fenced code blocks should be surrounded by blank lines
  MD032: true   # Lists should be surrounded by blank lines
  MD034: true   # Bare URL used
  MD035: true   # Horizontal rule style
  MD036: true   # Emphasis used instead of a heading
  MD037: true   # Spaces inside emphasis markers
  MD038: true   # Spaces inside code span elements
  MD039: true   # Spaces inside link text
  MD040: true   # Fenced code blocks should have a language specified
  MD042: true   # No empty links
  MD043: false  # Required heading structure - disabled for flexibility
  MD044: true   # Proper names should have the correct capitalization
  MD045: true   # Images should have alternate text (alt text)
  MD046: true   # Code block style
  MD047: true   # Files should end with a single newline character
  MD048: true   # Code fence style
  MD049: true   # Emphasis style
  MD050: true   # Strong style
  MD051: true   # Link fragments should be valid
  MD052: true   # Reference links and images should use a label that is defined
  MD053: true   # Link and image reference definitions should be needed

# Ignore patterns
ignores:
  - "target/**"
  - "node_modules/**"
  - ".git/**"
