[workspace]
members = [
    "firmware",
    "host-tool",
    "protocol"
]

[package]
name = "stm32g4-flash-programmer-workspace"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "png_to_bitmap"
path = "tools/png_to_bitmap_real.rs"

[dependencies]
image = "0.24"
