#!/bin/bash
# W25Q128JV Flash Programming Script
# Generated by Flash Composer

FLASH_IMAGE="w25q128jv_complete.bin"

echo "🚀 Programming W25Q128JV Flash Memory"
echo "===================================="

if [ ! -f "$FLASH_IMAGE" ]; then
    echo "❌ Flash image not found: $FLASH_IMAGE"
    exit 1
fi

echo "📄 Flash image: $FLASH_IMAGE"
echo "📏 Size: $(stat -f%z "$FLASH_IMAGE" 2>/dev/null || stat -c%s "$FLASH_IMAGE" 2>/dev/null) bytes"
echo

echo "⚡ Programming complete flash image..."
st-flash write "$FLASH_IMAGE" 0x00000000

if [ $? -eq 0 ]; then
    echo "✅ Flash programming completed successfully!"
else
    echo "❌ Flash programming failed!"
    exit 1
fi
